// Playwright MCP. Isolated simulation workspace; never target a user data directory.
async page => {
  const results=[],errors=[],suffix=Date.now().toString(36),assert=(ok,message)=>{if(!ok)throw Error(message);};
  page.on('pageerror',e=>errors.push(e.message));
  const record=name=>results.push(name),close=()=>page.locator('dialog[open]').waitFor({state:'hidden'});
  const data=()=>page.evaluate(async()=>await(await fetch('/api/task-workspace')).json());
  await page.unrouteAll({behavior:'wait'});await page.setViewportSize({width:1440,height:1000});await page.goto('http://127.0.0.1:8783');
  await page.waitForFunction(()=>document.querySelector('#connection').dataset.connected==='true');
  const names=['Alex '+suffix,'Sam '+suffix];
  for(const name of names){await page.locator('[data-view=accounts]').click();await page.locator('#primary').click();await page.locator('#editor [name=name]').fill(name);await page.locator('#editor [name=email]').fill(name.split(' ')[0]+suffix+'@example.invalid');await page.locator('#editor [type=submit]').click();await close();}
  await page.locator('[data-view=task_groups]').click();await page.locator('#primary').click();
  assert(await page.locator('dialog[open] input:visible,dialog[open] textarea:visible,dialog[open] select:visible').count()===4,'Group creation should have four fields');
  await page.locator('dialog[open] [name=name]').fill('Original workflow '+suffix);await page.locator('dialog[open] [name=products]').fill('B012345678');await page.locator('dialog[open]').getByRole('button',{name:'Create group',exact:true}).click();await close();
  const id=await page.evaluate(()=>groupId);record('Four-field group creation; no purchase-goal controls');
  const accountFolder=await page.evaluate(async names=>{const folder=await api('folders','POST',{name:'Smoke accounts '+Date.now(),resource_kind:'accounts'});await api('organization/members','POST',{folder_id:folder.id,ids:state.accounts.filter(a=>names.includes(a.name)).map(a=>a.id)});await refresh(true);return folder.id;},names);
  await page.locator('[data-work-add]').first().click();await page.locator('[data-assignment-account=account_group]').click();await page.locator('#assignment-editor [name=account_group_id]').selectOption(accountFolder);await page.locator('#assignment-editor [name=count]').fill('2');await page.locator('#assignment-editor summary').first().click();
  await page.locator('#assignment-editor [name=checkout_mode]').selectOption('monitor');await page.waitForFunction(()=>!document.querySelector('#assignment-editor [type=submit]').disabled);await page.locator('#assignment-editor [type=submit]').click();await close();
  let tasks=(await data()).tasks.filter(t=>t.group_id===id);assert(tasks.length===2,'Create one independent task per account');record('Multi-account task creation');
  const first=tasks[0].id,second=tasks[1].id,row=key=>page.locator(`[data-task-row="${key}"]`);
  await row(first).locator('[data-work-details]').click();await page.locator('[data-task-edit]').click();await page.locator('dialog[open] [name=quantity]').fill('2');await page.locator('dialog[open] summary').click();await page.locator('dialog[open] [name=max_total]').fill('75');await page.getByRole('button',{name:'Save task',exact:true}).click();await close();
  await page.locator('[data-work-tab=checkout]').click();await page.locator('[data-work-settings] [name=max_total]').fill('125');await page.getByRole('button',{name:'Save settings',exact:true}).click();await page.waitForFunction(()=>state.groups.find(g=>g.id===groupId).max_total===125);
  tasks=(await data()).tasks;assert(tasks.find(t=>t.id===first).quantity===2&&tasks.find(t=>t.id===first).max_total===75,'Task override');assert(tasks.find(t=>t.id===second).quantity===1&&tasks.find(t=>t.id===second).max_total===null,'Other task inherits');record('Independent task settings and live group-limit inheritance');
  await row(first).locator('[data-work-command=start]').click();await page.waitForFunction(key=>state.active.includes(key),first);assert(!(await data()).active.includes(second),'Single start must not start sibling');
  assert(await page.getByRole('button',{name:'Save settings',exact:true}).isDisabled(),'Running group must lock editing');await row(first).locator('[data-work-command=stop]').click();await page.waitForFunction(key=>!state.active.includes(key),first);record('Independent start/stop and frozen running group');
  await page.locator('[data-work-bulk=start]').click();await page.waitForFunction(ids=>ids.every(id=>state.active.includes(id)),[first,second]);await page.locator('[data-work-bulk=stop]').click();await page.waitForFunction(ids=>ids.every(id=>!state.active.includes(id)),[first,second]);record('Start all and stop all execute independent accounts');
  await row(first).locator('[data-work-select]').check();await page.locator('[data-work-bulk=start]').click();await page.waitForFunction(key=>state.active.includes(key),first);assert(!(await data()).active.includes(second),'Selection isolation');await page.locator('[data-work-bulk=stop]').click();await page.waitForFunction(key=>!state.active.includes(key),first);await row(first).locator('[data-work-select]').uncheck();record('Selected task controls');
  await page.locator('[data-work-tab=general]').click();await page.locator('[data-work-settings] [name=name]').fill('Unsaved draft');await page.locator('[data-work-add]').first().focus();await page.waitForTimeout(4200);assert(await page.locator('[data-work-settings] [name=name]').inputValue()==='Unsaved draft','Polling must preserve draft');record('Draft and focus survive background refresh');
  await page.locator('[data-work-add]').first().click();await page.keyboard.press('Escape');await close();assert(await page.locator('[data-work-add]').first().evaluate(el=>document.activeElement===el),'Dialog focus restoration');record('Keyboard Escape and focus return');
  await page.route('**/api/task-workspace',async route=>{const response=await route.fetch(),body=await response.json();const failed=body.tasks.find(t=>t.id===first);failed.status='error';failed.message='Sign-in needs attention';await route.fulfill({response,json:body});});await page.waitForFunction(key=>state.tasks.find(t=>t.id===key)?.status==='error',first);assert((await row(first).innerText()).includes('Sign-in needs attention'),'Failure visible');assert(!(await row(second).innerText()).includes('Sign-in needs attention'),'Failure isolated');await page.unroute('**/api/task-workspace');record('Account-specific error display');
  await page.locator('[data-work-schedule]').click();await page.locator('[name=slots]').fill('10:00 - 10:30');await page.getByRole('button',{name:'Save',exact:true}).click();await close();assert((await data()).groups.find(g=>g.id===id).schedule.slots.length===1,'Schedule saved');await page.locator('[data-work-schedule]').click();await page.locator('[name=slots]').fill('');await page.getByRole('button',{name:'Save',exact:true}).click();await close();record('Schedule and clear schedule');
  // One virtual automatic simulation exercises the original task runner to confirmation.
  await page.locator('[data-work-add]').first().click();await page.locator('#assignment-editor summary').first().click();await page.locator('#assignment-editor [name=checkout_mode]').selectOption('automatic');await page.waitForFunction(()=>!document.querySelector('#assignment-editor [type=submit]').disabled);await page.locator('#assignment-editor [type=submit]').click();await close();
  const virtual=(await data()).tasks.find(t=>t.group_id===id&&!t.account_id);await row(virtual.id).locator('[data-work-command=start]').click();await page.waitForFunction(key=>state.tasks.find(t=>t.id===key)?.status==='completed',virtual.id);record('Automatic simulation reaches confirmed task result');
  await page.locator('[data-work-duplicate]').click();await page.waitForFunction(old=>groupId!==old,id);const copy=await page.evaluate(()=>groupId),copied=await data();assert(await page.locator('[data-work-settings] [name=name]').inputValue()===copied.groups.find(g=>g.id===copy).name,'Draft must not leak into another group');assert(copied.tasks.filter(t=>t.group_id===copy).length===3,'Duplicate includes all tasks');assert(copied.tasks.filter(t=>t.group_id===copy).every(t=>t.simulation&&t.status==='idle'),'Duplicate resets execution');record('Safe group duplication');
  await page.setViewportSize({width:390,height:844});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Mobile overflow');await page.screenshot({path:'C:/Users/justi/Documents/Python/Retail Bot Overhaul/artifacts/overhaul/restored-mobile.png',fullPage:true});await page.locator('[data-work-add]').first().click();assert(await page.locator('dialog[open]').evaluate(el=>el.scrollWidth<=el.clientWidth),'Mobile editor overflow');await page.keyboard.press('Escape');record('390px workspace and task editor');
  await page.setViewportSize({width:1440,height:1000});await page.screenshot({path:'C:/Users/justi/Documents/Python/Retail Bot Overhaul/artifacts/overhaul/restored-desktop.png',fullPage:true});
  await page.locator('[data-work-delete]').click();assert(await page.locator('dialog[open] [data-cancel]').evaluate(el=>document.activeElement===el),'Destructive cancel focus');await page.locator('dialog[open] [type=submit]').click();await close();await page.waitForFunction(()=>groupId===null);assert(!(await data()).groups.some(g=>g.id===copy),'Group deleted');assert(!(await data()).tasks.some(t=>t.group_id===copy),'No orphan tasks');record('Confirmed group and task deletion');
  for(const target of ['home','accounts','checkouts','events','tools','settings','task_groups']){await page.locator(`[data-view=${target}]`).click();assert((await page.locator('#screen').innerText()).length>10,'Empty navigation '+target);}record('Navigation preserved');
  assert(errors.length===0,'Browser errors: '+errors.join('; '));return {results,errors};
}
