// Isolated Playwright MCP fixture workspace. No live tasks or purchases.
async page => {
  const assert=(ok,message)=>{if(!ok)throw Error(message);},results=[],errors=[],tag=Date.now().toString(36);
  page.on('pageerror',e=>errors.push(e.message));
  await page.setViewportSize({width:1440,height:1000});await page.goto('http://127.0.0.1:8783');
  await page.waitForFunction(()=>document.querySelector('#connection').dataset.connected==='true');
  const fixture=await page.evaluate(async tag=>{
    const post=async(path,value)=>{const response=await fetch('/api/'+path,{method:'POST',headers:{'Content-Type':'application/json','X-Retail-Client':'dashboard'},body:JSON.stringify(value)});const data=await response.json();if(!response.ok)throw Error(JSON.stringify(data));return data;};
    const accounts=[],profiles=[];
    for(let i=0;i<2;i++){accounts.push(await post('accounts',{name:`Profile account ${i} ${tag}`,email:`profile-${i}-${tag}@example.invalid`}));profiles.push(await post('profiles',{name:`Checkout ${i} ${tag}`,email:`profile-${i}-${tag}@example.invalid`}));}
    const profileGroup=await post('folders',{name:'Profiles '+tag,resource_kind:'profiles'}),accountGroup=await post('folders',{name:'Accounts '+tag,resource_kind:'accounts'});
    await post('organization/members',{folder_id:profileGroup.id,ids:profiles.map(x=>x.id)});await post('organization/members',{folder_id:accountGroup.id,ids:accounts.map(x=>x.id)});
    const group=await post('groups',{name:'Tabs '+tag,products:'B012345678',max_total:100});return {accounts,profiles,profileGroup,accountGroup,group};
  },tag);
  await page.evaluate(()=>refresh(true));await page.locator(`[data-work-open="${fixture.group.id}"]`).first().click();
  const tab=key=>page.locator(`[data-work-tab=${key}]`),form=page.locator('[data-work-settings]');
  assert((await page.locator('[data-work-tab]').allTextContents()).join(',')==='General,Monitoring,Checkout,Advanced','Four group tabs');
  await form.locator('[name=name]').fill('Saved tabs '+tag);
  await tab('monitoring').click();await form.locator('[name=products]').fill('B012345678;30');await form.locator('[name=delay_ms]').fill('5000');await form.locator('[name=min_price]').fill('5');await form.locator('[name=max_price]').fill('40');await form.locator('[name=allow_used]').check();
  await tab('checkout').click();await form.locator('[name=quantity]').fill('2');await form.locator('[name=max_total]').fill('120');await form.locator('[name=max_errors]').fill('7');await form.locator('[name=retry_delay_ms]').fill('4000');await form.locator('[name=max_checkouts]').fill('3');
  await tab('advanced').click();await form.locator('[name=mode]').selectOption('deals');await form.locator('[name=only_freebies]').uncheck();await form.locator('[name=min_discount]').fill('10');await form.locator('[name=min_savings]').fill('2');await form.locator('[name=notify_offer]').check();await form.locator('[name=monitor_concurrency]').fill('4');
  await tab('general').click();assert(await form.locator('[name=name]').inputValue()==='Saved tabs '+tag,'Draft retained across tabs');await page.waitForTimeout(2200);assert(await form.locator('[name=name]').inputValue()==='Saved tabs '+tag,'Draft retained across polling');
  await form.locator('[type=submit]').click();await page.waitForFunction(id=>state.groups.find(g=>g.id===id)?.quantity===2,fixture.group.id);
  const saved=await page.evaluate(id=>state.groups.find(g=>g.id===id),fixture.group.id);
  assert(saved.name==='Saved tabs '+tag&&saved.delay_ms===5000&&saved.max_total===120&&saved.allow_used&&saved.max_errors===7&&saved.min_discount===10&&saved.monitor_concurrency===4,'All group settings persisted');results.push('Four tabs save their settings together without losing drafts');
  await tab('general').focus();await page.keyboard.press('ArrowRight');assert(await tab('monitoring').getAttribute('aria-selected')==='true','Keyboard tab switching');results.push('Accessible keyboard tabs');
  await form.locator('[name=delay_ms]').fill('1');await tab('general').click();await form.locator('[type=submit]').click();assert(await tab('monitoring').getAttribute('aria-selected')==='true','Hidden invalid control is revealed');await form.locator('[name=delay_ms]').fill('5000');results.push('Validation reveals the tab containing the invalid field');
  await page.locator('[data-work-add]').first().click();const editor=page.locator('#assignment-editor');
  assert(await editor.locator('[name=quantity]').inputValue()==='2'&&await editor.locator('[name=retry_delay_ms]').inputValue()==='4000','New tasks use group checkout defaults');
  await editor.locator('[name=profile_id]').selectOption(fixture.profiles[0].id);await editor.locator('[name=match_profiles]').check();
  await page.waitForFunction(name=>document.querySelector('.assignment-preview')?.textContent.includes(name),fixture.accounts[0].name);assert((await editor.locator('.assignment-preview').innerText()).includes('Matching email'),'Email matching preview');
  await editor.locator('[type=submit]').click();await editor.waitFor({state:'hidden'});
  let tasks=await page.evaluate(async id=>(await(await fetch('/api/task-workspace')).json()).tasks.filter(t=>t.group_id===id),fixture.group.id);assert(tasks.length===1&&tasks[0].profile_id===fixture.profiles[0].id&&tasks[0].account_id===fixture.accounts[0].id,'Single profile assignment persisted');results.push('Single checkout profile with email-matched account');
  await page.locator('[data-work-add]').first().click();await editor.locator('[data-assignment-profile=profile_group]').click();await editor.locator('[name=profile_group_id]').selectOption(fixture.profileGroup.id);await editor.locator('[name=match_profiles]').check();await editor.locator('[name=count]').fill('2');await editor.locator('[name=distribution]').selectOption('one_to_one');
  await page.waitForFunction(()=>document.querySelectorAll('.assignment-preview tbody tr').length===2&&!document.querySelector('#assignment-editor [type=submit]').disabled);
  await editor.locator('[type=submit]').click();await editor.waitFor({state:'hidden'});
  tasks=await page.evaluate(async id=>(await(await fetch('/api/task-workspace')).json()).tasks.filter(t=>t.group_id===id),fixture.group.id);assert(tasks.length===3&&new Set(tasks.map(t=>t.account_id)).size===2&&new Set(tasks.map(t=>t.profile_id)).size===2,'One-to-one profile group assignments');results.push('Profile group creates one-to-one account/profile tasks');
  await page.locator('[data-work-add]').first().click();await editor.locator('[data-assignment-account=account_group]').click();await editor.locator('[name=account_group_id]').selectOption(fixture.accountGroup.id);await editor.locator('[name=count]').fill('2');await editor.locator('[name=distribution]').selectOption('random');
  await page.waitForFunction(()=>document.querySelectorAll('.assignment-preview tbody tr').length===2&&!document.querySelector('#assignment-editor [type=submit]').disabled);const before=await editor.locator('.assignment-preview').innerText();await editor.locator('summary').first().click();await editor.locator('[name=max_total]').fill('80');await page.waitForTimeout(250);assert(await editor.locator('.assignment-preview').innerText()===before,'Random mapping stable between preview updates');await editor.locator('[type=submit]').click();await editor.waitFor({state:'hidden'});results.push('Manual account group and stable randomized preview');
  const taskRow=page.locator('[data-task-row]').filter({hasText:fixture.profiles[0].name}).first();await taskRow.locator('[data-work-details]').click();await page.locator('[data-task-edit]').click();await page.locator('dialog[open] [name=profile_id]').selectOption(fixture.profiles[1].id);await page.getByRole('button',{name:'Save task',exact:true}).click();await page.locator('dialog[open]').waitFor({state:'hidden'});results.push('Existing task checkout profile remains editable');
  await page.locator('[data-work-add]').first().click();await editor.locator('[data-assignment-profile=profile_group]').click();await page.waitForFunction(()=>document.querySelector('.assignment-errors').textContent.includes('Choose a profile group'));assert(await editor.locator('[type=submit]').isDisabled(),'Empty profile group must block creation');await page.keyboard.press('Escape');results.push('Missing group selections cannot create accidental assignments');
  await page.setViewportSize({width:390,height:844});for(const key of ['general','monitoring','checkout','advanced']){await tab(key).click();assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'Mobile tab overflow '+key);}
  await page.locator('[data-work-add]').first().click();assert(await editor.evaluate(el=>el.scrollWidth<=el.clientWidth),'Mobile assignment overflow');await page.screenshot({path:'C:/Users/justi/Documents/Python/Retail Bot Overhaul/artifacts/overhaul/profile-assignment-mobile.png',fullPage:true});await page.keyboard.press('Escape');results.push('All tabs and assignment editor fit 390px');
  await page.setViewportSize({width:1440,height:1000});await tab('monitoring').click();await page.screenshot({path:'C:/Users/justi/Documents/Python/Retail Bot Overhaul/artifacts/overhaul/group-tabs-desktop.png',fullPage:true});
  assert(!errors.length,'Browser errors '+errors.join(';'));return {results,errors,groupId:fixture.group.id};
}
